Import eglextchromium.h from Chromium.
In order to support the (currently unregistered) Chromium-specific EGL
extension eglGetSyncValuesCHROMIUM on Intel systems, we need to import
the Chromium header that defines it.  The file was downloaded from

https://chromium.googlesource.com/chromium/chromium/+/trunk/ui/gl/EGL/eglextchromium.h

It is subject to the license found at

https://chromium.googlesource.com/chromium/chromium/+/trunk/LICENSE

I have imported the header file and added the license text to the top.
The only change was to remove the Chromium specific defines for
GPU_EGL_EGLEXTCHROMIUM_H_  If I leave them in, compiling Mesa fails:

make[2]: Entering directory `/home/sarah/git/mesa/src/egl/drivers/dri2'
  CC       egl_dri2.lo
In file included from ../../../../include/EGL/eglext.h:649:0,
                 from ../../../../src/egl/main/egltypedefs.h:37,
                 from ../../../../src/egl/main/eglconfig.h:37,
                 from egl_dri2.h:67,
                 from egl_dri2.c:52:
../../../../include/EGL/eglextchromium.h:60:38: error: no macro name given in #define directive
 #define  // GPU_EGL_EGLEXTCHROMIUM_H_
                                      ^
../../../../include/EGL/eglextchromium.h:31:0: error: unterminated #ifndef
 #ifndef GPU_EGL_EGLEXTCHROMIUM_H_
 ^
make[2]: *** [egl_dri2.lo] Error 1
make[2]: Leaving directory `/home/sarah/git/mesa/src/egl/drivers/dri2'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/sarah/git/mesa/src'
make: *** [all-recursive] Error 1

Signed-off-by: Sarah Sharp <sarah.a.sharp@linux.intel.com>
Cc: Chad Versace <chad.versace@linux.intel.com>
Cc: Jamey Sharp <jamey@minilop.net>
Cc: Ian Romanick <idr@freedesktop.org>
Cc: Stéphane Marchesin <stephane.marchesin@gmail.com>